"use client";
import{CalendarDays,CheckCircle2,Clock3,X}from"lucide-react";
import type{AgendaAppointmentDetail}from"./AgendaAppointmentDetails.types";
import styles from"./AgendaAppointmentDetails.module.css";
type Props={appointment:AgendaAppointmentDetail;statusLabels:Record<string,string>;onClose:()=>void};
const dateTime=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const time=(v:string)=>new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"}).format(new Date(v));
const duration=(a:string,b:string)=>{const m=Math.max(0,Math.round((new Date(b).getTime()-new Date(a).getTime())/60000));if(m<60)return`${m} min`;const h=Math.floor(m/60),r=m%60;return r?`${h}h ${r}min`:`${h}h`};
export default function AgendaAppointmentHero({appointment,statusLabels,onClose}:Props){const appointmentStyle=appointment.tipo?({"--appointment-color":appointment.tipo.cor}as React.CSSProperties):undefined;return <header className={styles.hero}><div className={styles.heroGlow}/><div className={styles.heroTop}><div className={styles.heroIcon}><CalendarDays size={22}/></div><div className={styles.heroCopy}><div className={styles.badges}><span className={styles.statusBadge}>{statusLabels[appointment.status]||appointment.status}</span>{appointment.tipo?<span className={styles.typeBadge} style={appointmentStyle}>{appointment.tipo.nome}</span>:null}</div><h2 id="appointment-details-title">{appointment.titulo}</h2><p>{dateTime(appointment.inicio_at)} · {duration(appointment.inicio_at,appointment.fim_at)}</p></div><button type="button" className={styles.closeButton} onClick={onClose} aria-label="Fechar detalhes"><X size={18}/></button></div><div className={styles.scheduleStrip}><div><CalendarDays size={17}/><span><small>Início</small><strong>{dateTime(appointment.inicio_at)}</strong></span></div><div><Clock3 size={17}/><span><small>Término</small><strong>{time(appointment.fim_at)}</strong></span></div><div><CheckCircle2 size={17}/><span><small>Confirmação</small><strong>{statusLabels[appointment.confirmacao_status]||appointment.confirmacao_status||"Pendente"}</strong></span></div></div></header>}
