"use client";
import{Bell,CheckCircle2,History,UserRound,UsersRound}from"lucide-react";
import type{AgendaAppointmentDetail,AgendaAppointmentDetailHistory}from"./AgendaAppointmentDetails.types";
import styles from"./AgendaAppointmentDetails.module.css";
type Props={appointment:AgendaAppointmentDetail;customerLabel:string};
const dateTime=(v?:string|null)=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"Não informado";
const reminderLabel=(m:number)=>m>=1440&&m%1440===0?`${m/1440} dia${m===1440?"":"s"} antes`:m>=60&&m%60===0?`${m/60} hora${m===60?"":"s"} antes`:`${m} min antes`;
const channelLabel=(v:string)=>v==="whatsapp"?"WhatsApp":v==="email"?"E-mail":"Sistema";
const recipientLabel=(v:string,label:string)=>v==="cliente"?label:v==="participantes"?"Participantes":"Responsável";
function autorHistorico(item:AgendaAppointmentDetailHistory,appointment:AgendaAppointmentDetail){const respondido=appointment.metadata_json?.confirmacao_whatsapp?.respondido_em;const diff=respondido?Math.abs(new Date(item.created_at).getTime()-new Date(respondido).getTime()):Number.POSITIVE_INFINITY;const contato=item.acao==="status_alterado"&&item.status_novo==="confirmado"&&(item.usuario_id==null||diff<=300000);if(!contato)return item.usuario_nome||"Sistema";const nome=appointment.contato?.nome||appointment.nome_cliente;return nome?`${nome} (contato)`:"Contato"}
function DetailValue({label,value}:{label:string;value?:string|null}){return <div className={styles.detailValue}><span>{label}</span><strong>{value||"Não informado"}</strong></div>}
export default function AgendaAppointmentSecondarySections({appointment,customerLabel}:Props){return <>{appointment.participantes.length>0?<section className={styles.section}><div className={styles.sectionTitle}><UsersRound size={17}/><div><h3>Participantes</h3><p>Pessoas adicionais neste compromisso.</p></div></div><div className={styles.compactList}>{appointment.participantes.map((p,i)=><div key={`${p.nome}-${i}`}><div className={styles.smallAvatar}><UserRound size={15}/></div><span><strong>{p.nome}</strong><small>{[p.papel,p.email,p.telefone].filter(Boolean).join(" · ")||"Participante"}</small></span>{p.status?<em>{p.status}</em>:null}</div>)}</div></section>:null}{appointment.lembretes.length>0?<section className={styles.section}><div className={styles.sectionTitle}><Bell size={17}/><div><h3>Lembretes</h3><p>Avisos configurados para este agendamento.</p></div></div><div className={styles.compactList}>{appointment.lembretes.map((r,i)=><div key={`${r.canal}-${i}`}><div className={styles.smallAvatar}><Bell size={15}/></div><span><strong>{channelLabel(r.canal)} · {reminderLabel(r.antecedencia_minutos)}</strong><small>Para {recipientLabel(r.destinatario_tipo,customerLabel)}{r.agendado_para?` · ${dateTime(r.agendado_para)}`:""}</small></span>{r.status?<em>{r.status}</em>:null}</div>)}</div></section>:null}{appointment.resultado||appointment.observacoes_internas?<section className={styles.section}><div className={styles.sectionTitle}><CheckCircle2 size={17}/><div><h3>Resultado e informações internas</h3><p>Registro final do atendimento.</p></div></div><div className={styles.internalGrid}><DetailValue label="Resultado" value={appointment.resultado}/>{appointment.observacoes_internas?<div className={styles.internalNote}><span>Observações internas</span><p>{appointment.observacoes_internas}</p></div>:null}</div></section>:null}<section className={styles.section}><div className={styles.sectionTitle}><History size={17}/><div><h3>Histórico</h3><p>Movimentações registradas neste agendamento.</p></div></div>{appointment.historico.length>0?<div className={styles.timeline}>{appointment.historico.map(item=><div key={item.id}><span/><div><strong>{item.acao.replaceAll("_"," ")}</strong><p>{item.descricao||"Alteração registrada."}</p><small>{autorHistorico(item,appointment)} · {dateTime(item.created_at)}</small></div></div>)}</div>:<div className={styles.empty}>Sem alterações registradas.</div>}</section></>}
