-- Etapa 1 do estoque ERP: fundacao multi-deposito, lotes, reservas,
-- documentos, razao imutavel, custos e operacoes idempotentes.

alter table public.estoque_itens
  add column if not exists sku text,
  add column if not exists codigo_barras text,
  add column if not exists categoria_id uuid,
  add column if not exists marca_id uuid,
  add column if not exists controla_lote boolean not null default false,
  add column if not exists controla_validade boolean not null default false,
  add column if not exists controla_serie boolean not null default false,
  add column if not exists versao integer not null default 1;

create table if not exists public.estoque_categorias (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nome text not null,
  categoria_pai_id uuid references public.estoque_categorias(id) on delete restrict,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (empresa_id, nome)
);

create table if not exists public.estoque_marcas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (empresa_id, nome)
);

create table if not exists public.estoque_depositos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  codigo text not null,
  nome text not null,
  descricao text,
  principal boolean not null default false,
  permite_saldo_negativo boolean not null default false,
  ativo boolean not null default true,
  created_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, codigo),
  unique (empresa_id, id)
);

create unique index if not exists estoque_depositos_principal_uk
  on public.estoque_depositos (empresa_id) where principal and ativo;

create table if not exists public.estoque_localizacoes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  deposito_id uuid not null,
  codigo text not null,
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (empresa_id, deposito_id, codigo),
  unique (empresa_id, id),
  foreign key (empresa_id, deposito_id)
    references public.estoque_depositos(empresa_id, id) on delete cascade
);

create table if not exists public.estoque_lotes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  codigo text not null,
  fabricado_em date,
  validade date,
  fabricante text,
  bloqueado boolean not null default false,
  motivo_bloqueio text,
  created_at timestamptz not null default now(),
  unique (empresa_id, estoque_item_id, codigo),
  unique (empresa_id, id)
);

create table if not exists public.estoque_saldos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  deposito_id uuid not null,
  localizacao_id uuid,
  lote_id uuid,
  numero_serie text,
  saldo_fisico numeric(18, 6) not null default 0 check (saldo_fisico >= 0),
  saldo_reservado numeric(18, 6) not null default 0 check (saldo_reservado >= 0),
  saldo_transito numeric(18, 6) not null default 0 check (saldo_transito >= 0),
  custo_medio numeric(18, 6) not null default 0 check (custo_medio >= 0),
  versao bigint not null default 1,
  updated_at timestamptz not null default now(),
  foreign key (empresa_id, deposito_id) references public.estoque_depositos(empresa_id, id),
  foreign key (empresa_id, localizacao_id) references public.estoque_localizacoes(empresa_id, id),
  foreign key (empresa_id, lote_id) references public.estoque_lotes(empresa_id, id),
  check (saldo_reservado <= saldo_fisico),
  check (numero_serie is null or saldo_fisico <= 1)
);

create unique index if not exists estoque_saldos_dimensoes_uk on public.estoque_saldos (
  empresa_id, estoque_item_id, deposito_id,
  coalesce(localizacao_id, '00000000-0000-0000-0000-000000000000'::uuid),
  coalesce(lote_id, '00000000-0000-0000-0000-000000000000'::uuid),
  coalesce(numero_serie, '')
);

create table if not exists public.estoque_documentos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  numero bigint generated by default as identity,
  tipo text not null check (tipo in ('saldo_inicial','entrada','saida','ajuste','transferencia','reserva','consumo','liberacao','estorno')),
  status text not null default 'rascunho' check (status in ('rascunho','confirmado','cancelado','estornado')),
  origem_tipo text,
  origem_id uuid,
  idempotency_key text,
  observacao text,
  confirmado_em timestamptz,
  estornado_por_id uuid references public.estoque_documentos(id) on delete restrict,
  created_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (empresa_id, id),
  unique (empresa_id, idempotency_key)
);

create table if not exists public.estoque_documento_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  documento_id uuid not null,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  deposito_origem_id uuid,
  deposito_destino_id uuid,
  localizacao_origem_id uuid,
  localizacao_destino_id uuid,
  lote_id uuid,
  numero_serie text,
  quantidade numeric(18, 6) not null check (quantidade > 0),
  custo_unitario numeric(18, 6) check (custo_unitario is null or custo_unitario >= 0),
  created_at timestamptz not null default now(),
  foreign key (empresa_id, documento_id) references public.estoque_documentos(empresa_id, id) on delete cascade
);

create table if not exists public.estoque_reservas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  deposito_id uuid not null,
  lote_id uuid,
  quantidade numeric(18, 6) not null check (quantidade > 0),
  consumida numeric(18, 6) not null default 0 check (consumida >= 0),
  status text not null default 'ativa' check (status in ('ativa','consumida','liberada','expirada')),
  origem_tipo text not null,
  origem_id uuid not null,
  expira_em timestamptz,
  created_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  foreign key (empresa_id, deposito_id) references public.estoque_depositos(empresa_id, id),
  foreign key (empresa_id, lote_id) references public.estoque_lotes(empresa_id, id),
  check (consumida <= quantidade)
);

create table if not exists public.estoque_custos_historico (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  documento_id uuid references public.estoque_documentos(id) on delete restrict,
  custo_anterior numeric(18, 6) not null,
  custo_novo numeric(18, 6) not null,
  quantidade_entrada numeric(18, 6),
  created_at timestamptz not null default now()
);

create table if not exists public.estoque_configuracoes (
  empresa_id uuid primary key references public.empresas(id) on delete cascade,
  modo text not null default 'simples' check (modo in ('simples','avancado')),
  metodo_custo text not null default 'medio' check (metodo_custo in ('medio','fifo')),
  bloquear_negativo boolean not null default true,
  exigir_justificativa_ajuste boolean not null default true,
  selecionar_lote_fefo boolean not null default true,
  dias_alerta_validade integer not null default 60 check (dias_alerta_validade >= 0),
  updated_by uuid references public.usuarios(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists estoque_saldos_item_deposito_idx on public.estoque_saldos (empresa_id, estoque_item_id, deposito_id);
create index if not exists estoque_lotes_validade_idx on public.estoque_lotes (empresa_id, validade) where not bloqueado;
create index if not exists estoque_documentos_data_idx on public.estoque_documentos (empresa_id, created_at desc);
create index if not exists estoque_documento_itens_documento_idx on public.estoque_documento_itens (empresa_id, documento_id);
create index if not exists estoque_reservas_origem_idx on public.estoque_reservas (empresa_id, origem_tipo, origem_id);
create index if not exists estoque_reservas_ativas_idx on public.estoque_reservas (empresa_id, estoque_item_id, deposito_id) where status = 'ativa';

insert into public.estoque_depositos (empresa_id, codigo, nome, principal)
select e.id, 'PRINCIPAL', 'Depósito principal', true
from public.empresas e
where not exists (select 1 from public.estoque_depositos d where d.empresa_id = e.id);

insert into public.estoque_configuracoes (empresa_id)
select e.id from public.empresas e on conflict (empresa_id) do nothing;

-- Converte o saldo do MVP em saldo inicial auditavel.
with base as (
  select i.empresa_id, i.id item_id, i.saldo, i.custo_unitario, d.id deposito_id
  from public.estoque_itens i
  join public.estoque_depositos d on d.empresa_id = i.empresa_id and d.principal
  where i.saldo > 0
)
insert into public.estoque_saldos (empresa_id, estoque_item_id, deposito_id, saldo_fisico, custo_medio)
select empresa_id, item_id, deposito_id, saldo, custo_unitario from base
on conflict do nothing;

create or replace function public.estoque_confirmar_documento(
  p_empresa_id uuid, p_documento_id uuid, p_usuario_id uuid default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_doc public.estoque_documentos%rowtype;
  v_linha record;
  v_saldo public.estoque_saldos%rowtype;
  v_delta numeric(18,6);
  v_antes numeric(18,6);
  v_depois numeric(18,6);
  v_total integer := 0;
begin
  select * into v_doc from public.estoque_documentos
   where id = p_documento_id and empresa_id = p_empresa_id for update;
  if not found then raise exception 'Documento nao encontrado.'; end if;
  if v_doc.status = 'confirmado' then return jsonb_build_object('documento_id', v_doc.id, 'idempotente', true); end if;
  if v_doc.status <> 'rascunho' then raise exception 'Documento nao pode ser confirmado.'; end if;

  for v_linha in select * from public.estoque_documento_itens
    where empresa_id = p_empresa_id and documento_id = v_doc.id order by estoque_item_id
  loop
    select coalesce(sum(saldo_fisico), 0) into v_antes from public.estoque_saldos
      where empresa_id=p_empresa_id and estoque_item_id=v_linha.estoque_item_id;
    if v_doc.tipo = 'transferencia' then
      if v_linha.deposito_origem_id is null or v_linha.deposito_destino_id is null or v_linha.deposito_origem_id = v_linha.deposito_destino_id then
        raise exception 'Informe depositos de origem e destino diferentes.';
      end if;
      perform public.estoque_aplicar_delta(p_empresa_id, v_linha.estoque_item_id, v_linha.deposito_origem_id, v_linha.lote_id, -v_linha.quantidade, coalesce(v_linha.custo_unitario, 0));
      perform public.estoque_aplicar_delta(p_empresa_id, v_linha.estoque_item_id, v_linha.deposito_destino_id, v_linha.lote_id, v_linha.quantidade, coalesce(v_linha.custo_unitario, 0));
    else
      v_delta := case
        when v_doc.tipo in ('entrada','saldo_inicial','estorno') then v_linha.quantidade
        when v_doc.tipo = 'ajuste' then v_linha.quantidade - coalesce((select sum(saldo_fisico) from public.estoque_saldos where empresa_id=p_empresa_id and estoque_item_id=v_linha.estoque_item_id and deposito_id=coalesce(v_linha.deposito_destino_id, v_linha.deposito_origem_id)), 0)
        else -v_linha.quantidade end;
      perform public.estoque_aplicar_delta(p_empresa_id, v_linha.estoque_item_id, coalesce(v_linha.deposito_destino_id, v_linha.deposito_origem_id), v_linha.lote_id, v_delta, coalesce(v_linha.custo_unitario, 0));
    end if;
    select coalesce(sum(saldo_fisico), 0) into v_depois from public.estoque_saldos
      where empresa_id=p_empresa_id and estoque_item_id=v_linha.estoque_item_id;
    insert into public.estoque_movimentacoes (
      empresa_id, estoque_item_id, tipo, quantidade, saldo_anterior, saldo_posterior,
      observacao, created_by, documento_id, deposito_id, lote_id, custo_unitario
    ) values (
      p_empresa_id, v_linha.estoque_item_id, v_doc.tipo, case when v_doc.tipo='ajuste' then abs(v_delta) else v_linha.quantidade end, v_antes, v_depois,
      v_doc.observacao, p_usuario_id, v_doc.id,
      coalesce(v_linha.deposito_destino_id, v_linha.deposito_origem_id), v_linha.lote_id, v_linha.custo_unitario
    );
    v_total := v_total + 1;
  end loop;
  if v_total = 0 then raise exception 'Documento sem itens.'; end if;
  update public.estoque_documentos set status='confirmado', confirmado_em=now() where id=v_doc.id;
  return jsonb_build_object('documento_id', v_doc.id, 'itens', v_total);
end $$;

create or replace function public.estoque_aplicar_delta(
  p_empresa_id uuid, p_item_id uuid, p_deposito_id uuid, p_lote_id uuid,
  p_delta numeric, p_custo_entrada numeric default 0
) returns void language plpgsql security definer set search_path = public as $$
declare v_atual public.estoque_saldos%rowtype; v_novo numeric; v_custo numeric;
begin
  if p_deposito_id is null then raise exception 'Deposito obrigatorio.'; end if;
  insert into public.estoque_saldos (empresa_id, estoque_item_id, deposito_id, lote_id)
  values (p_empresa_id, p_item_id, p_deposito_id, p_lote_id) on conflict do nothing;
  select * into v_atual from public.estoque_saldos where empresa_id=p_empresa_id and estoque_item_id=p_item_id
    and deposito_id=p_deposito_id and lote_id is not distinct from p_lote_id and localizacao_id is null and numero_serie is null for update;
  v_novo := v_atual.saldo_fisico + p_delta;
  if v_novo < v_atual.saldo_reservado then raise exception 'Saldo disponivel insuficiente.'; end if;
  v_custo := case when p_delta > 0 and p_custo_entrada > 0 and v_novo > 0
    then ((v_atual.saldo_fisico * v_atual.custo_medio) + (p_delta * p_custo_entrada)) / v_novo else v_atual.custo_medio end;
  update public.estoque_saldos set saldo_fisico=v_novo, custo_medio=v_custo, versao=versao+1, updated_at=now() where id=v_atual.id;
  update public.estoque_itens set saldo=(select coalesce(sum(saldo_fisico),0) from public.estoque_saldos where empresa_id=p_empresa_id and estoque_item_id=p_item_id),
    custo_unitario=v_custo, versao=versao+1 where empresa_id=p_empresa_id and id=p_item_id;
end $$;

-- Razao derivada dos documentos: nenhuma movimentacao pode ser editada/apagada.
alter table public.estoque_movimentacoes
  add column if not exists documento_id uuid references public.estoque_documentos(id) on delete restrict,
  add column if not exists deposito_id uuid references public.estoque_depositos(id) on delete restrict,
  add column if not exists lote_id uuid references public.estoque_lotes(id) on delete restrict,
  add column if not exists custo_unitario numeric(18,6);

alter table public.estoque_movimentacoes drop constraint if exists estoque_movimentacoes_tipo_check;
alter table public.estoque_movimentacoes add constraint estoque_movimentacoes_tipo_check
  check (tipo in ('saldo_inicial','entrada','saida','ajuste','transferencia','reserva','consumo','liberacao','estorno','venda','execucao'));

create or replace function public.estoque_movimento_imutavel() returns trigger language plpgsql as $$
begin raise exception 'Movimentacoes de estoque sao imutaveis; utilize estorno.'; end $$;
drop trigger if exists estoque_movimentacoes_bloquear_alteracao on public.estoque_movimentacoes;
create trigger estoque_movimentacoes_bloquear_alteracao before update or delete on public.estoque_movimentacoes
for each row execute function public.estoque_movimento_imutavel();

do $$ declare t text; begin
  foreach t in array array['estoque_categorias','estoque_marcas','estoque_depositos','estoque_localizacoes','estoque_lotes','estoque_saldos','estoque_documentos','estoque_documento_itens','estoque_reservas','estoque_custos_historico','estoque_configuracoes']
  loop execute format('alter table public.%I enable row level security', t); execute format('revoke all on public.%I from anon, authenticated', t); end loop;
end $$;

revoke execute on function public.estoque_aplicar_delta(uuid,uuid,uuid,uuid,numeric,numeric) from public, anon, authenticated;
revoke execute on function public.estoque_confirmar_documento(uuid,uuid,uuid) from public, anon, authenticated;
grant execute on function public.estoque_aplicar_delta(uuid,uuid,uuid,uuid,numeric,numeric) to service_role;
grant execute on function public.estoque_confirmar_documento(uuid,uuid,uuid) to service_role;

insert into public.permissoes (codigo, descricao)
values ('estoque.custos', 'Visualizar custos e valor financeiro do estoque'),
       ('estoque.configurar', 'Configurar depósitos, lotes e regras do estoque'),
       ('estoque.estornar', 'Estornar documentos e movimentações de estoque')
on conflict (codigo) do update set descricao = excluded.descricao;

insert into public.perfil_permissoes (perfil_empresa_id, permissao_codigo)
select p.id, pe.codigo from public.perfis_empresa p cross join public.permissoes pe
where lower(p.nome) = 'administrador' and pe.codigo in ('estoque.custos','estoque.configurar','estoque.estornar')
on conflict do nothing;
