create table if not exists public.usuario_permissoes (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  permissao_codigo text not null references public.permissoes(codigo) on delete cascade,
  efeito text not null check (efeito in ('permitir', 'bloquear')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (usuario_id, permissao_codigo)
);

create index if not exists usuario_permissoes_empresa_id_idx
  on public.usuario_permissoes (empresa_id);

create index if not exists usuario_permissoes_usuario_id_idx
  on public.usuario_permissoes (usuario_id);

insert into public.permissoes (codigo, descricao)
values
  ('dashboard.visualizar', 'Visualizar dashboard'),
  ('conversas.visualizar', 'Visualizar conversas'),
  ('conversas.assumir', 'Assumir conversas'),
  ('conversas.transferir', 'Transferir conversas'),
  ('conversas.atribuir', 'Atribuir responsavel em conversas'),
  ('conversas.encerrar', 'Encerrar conversas'),
  ('conversas.reabrir', 'Reabrir conversas'),
  ('conversas.exportar', 'Exportar conversa em PDF'),
  ('conversas.editar_contato', 'Editar dados do contato pela conversa'),
  ('conversas.gerenciar_etiquetas', 'Gerenciar etiquetas de conversa'),
  ('conversas.gerenciar_notas', 'Gerenciar notas internas de conversa'),
  ('conversas.gerenciar_listas', 'Gerenciar listas de conversa'),
  ('mensagens.visualizar', 'Visualizar mensagens'),
  ('mensagens.enviar', 'Enviar mensagens'),
  ('mensagens.enviar_midia', 'Enviar midias e arquivos'),
  ('mensagens.transcrever_audio', 'Transcrever audios'),
  ('mensagens.favoritar', 'Favoritar mensagens'),
  ('contatos.visualizar', 'Visualizar contatos'),
  ('contatos.criar', 'Criar contatos'),
  ('contatos.editar', 'Editar contatos'),
  ('contatos.excluir', 'Excluir contatos'),
  ('contatos.importar', 'Importar contatos'),
  ('contatos.exportar', 'Exportar contatos'),
  ('usuarios.visualizar', 'Visualizar usuarios'),
  ('usuarios.criar', 'Criar usuarios'),
  ('usuarios.editar', 'Editar usuarios'),
  ('usuarios.alterar_status', 'Alterar status de usuarios'),
  ('usuarios.alterar_perfis', 'Alterar perfis de usuarios'),
  ('usuarios.alterar_setores', 'Alterar setores de usuarios'),
  ('empresas.visualizar', 'Visualizar empresas'),
  ('empresas.criar', 'Criar empresas'),
  ('empresas.editar', 'Editar empresas'),
  ('empresas.alterar_status', 'Alterar status de empresas'),
  ('setores.visualizar', 'Visualizar setores'),
  ('setores.criar', 'Criar setores'),
  ('setores.editar', 'Editar setores'),
  ('setores.alterar_status', 'Alterar status de setores'),
  ('perfis.visualizar', 'Visualizar perfis'),
  ('perfis.criar', 'Criar perfis'),
  ('perfis.editar', 'Editar perfis'),
  ('perfis.alterar_permissoes', 'Alterar permissoes de perfis'),
  ('permissoes.visualizar', 'Visualizar configuracoes de permissoes'),
  ('permissoes.editar_empresa', 'Editar regras da empresa'),
  ('permissoes.editar_usuario', 'Editar excecoes por usuario'),
  ('whatsapp.integracao.visualizar', 'Visualizar integracao WhatsApp'),
  ('whatsapp.integracao.configurar', 'Configurar integracao WhatsApp'),
  ('whatsapp.perfil.visualizar', 'Visualizar perfil WhatsApp'),
  ('whatsapp.perfil.editar', 'Editar perfil WhatsApp'),
  ('whatsapp_templates.visualizar', 'Visualizar templates WhatsApp'),
  ('whatsapp_templates.criar', 'Criar templates WhatsApp'),
  ('whatsapp_templates.sincronizar', 'Sincronizar templates WhatsApp'),
  ('whatsapp.disparos.visualizar', 'Visualizar disparos WhatsApp'),
  ('whatsapp.disparos.enviar', 'Enviar disparos WhatsApp'),
  ('whatsapp.disparos.agendar', 'Agendar disparos WhatsApp'),
  ('whatsapp.disparos.cancelar', 'Cancelar disparos WhatsApp'),
  ('agendas.visualizar', 'Visualizar agendas'),
  ('agendas.criar', 'Criar agendas'),
  ('agendas.editar', 'Editar agendas'),
  ('agendas.arquivar', 'Arquivar agendas'),
  ('agendas.gerenciar_agendamentos', 'Gerenciar agendamentos'),
  ('fluxos.visualizar', 'Visualizar fluxos de automacao'),
  ('fluxos.criar', 'Criar fluxos de automacao'),
  ('fluxos.editar', 'Editar fluxos de automacao'),
  ('fluxos.ativar', 'Ativar ou pausar fluxos'),
  ('fluxos.arquivar', 'Arquivar fluxos'),
  ('fluxos.excluir', 'Excluir fluxos'),
  ('fluxos.gerenciar_gatilhos', 'Gerenciar gatilhos de fluxos'),
  ('fluxos.gerenciar_midias', 'Gerenciar midias de fluxos'),
  ('auditoria.visualizar', 'Visualizar auditoria')
on conflict (codigo) do update
set descricao = excluded.descricao;
