-- Etapa 3 do estoque ERP: parceiros, compras, vendas, devolucoes e inventarios.
-- Toda alteracao de saldo continua passando pelos documentos imutaveis da Etapa 1.

alter table public.estoque_documentos drop constraint if exists estoque_documentos_tipo_check;
alter table public.estoque_documentos add constraint estoque_documentos_tipo_check
  check (tipo in ('saldo_inicial','entrada','saida','ajuste','transferencia','reserva','consumo','liberacao','estorno','compra','venda','devolucao_compra','devolucao_venda','inventario'));
alter table public.estoque_documento_itens drop constraint if exists estoque_documento_itens_quantidade_check;
alter table public.estoque_documento_itens add constraint estoque_documento_itens_quantidade_check check (quantidade >= 0);

create table public.comercial_parceiros (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  contato_id uuid references public.contatos(id) on delete set null,
  tipo text not null default 'fornecedor' check (tipo in ('fornecedor','cliente','ambos')),
  tipo_pessoa text not null default 'juridica' check (tipo_pessoa in ('fisica','juridica')),
  nome text not null,
  nome_fantasia text,
  documento text,
  inscricao_estadual text,
  email text,
  telefone text,
  cep text,
  endereco text,
  numero text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  prazo_entrega_dias integer not null default 0 check (prazo_entrega_dias >= 0),
  observacao text,
  ativo boolean not null default true,
  versao integer not null default 1,
  created_by uuid references public.usuarios(id) on delete set null,
  updated_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, id)
);
create unique index comercial_parceiros_documento_uk on public.comercial_parceiros (empresa_id, documento)
  where documento is not null and documento <> '' and ativo;
create index comercial_parceiros_busca_idx on public.comercial_parceiros (empresa_id, tipo, ativo, nome);
create index comercial_parceiros_contato_idx on public.comercial_parceiros (empresa_id, contato_id) where contato_id is not null;

create table public.comercial_documentos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  numero bigint generated by default as identity,
  tipo text not null check (tipo in ('orcamento','pedido_venda','venda','pedido_compra','recebimento_compra','devolucao_venda','devolucao_compra')),
  status text not null default 'rascunho' check (status in ('rascunho','enviado','aprovado','parcial','concluido','cancelado')),
  parceiro_id uuid,
  contato_id uuid references public.contatos(id) on delete set null,
  documento_origem_id uuid references public.comercial_documentos(id) on delete restrict,
  deposito_id uuid,
  data_emissao date not null default current_date,
  validade_em date,
  previsao_em date,
  subtotal numeric(18,2) not null default 0 check (subtotal >= 0),
  desconto numeric(18,2) not null default 0 check (desconto >= 0),
  acrescimo numeric(18,2) not null default 0 check (acrescimo >= 0),
  frete numeric(18,2) not null default 0 check (frete >= 0),
  total numeric(18,2) not null default 0 check (total >= 0),
  valor_pago numeric(18,2) not null default 0 check (valor_pago >= 0),
  observacao text,
  idempotency_key text,
  versao integer not null default 1,
  aprovado_por uuid references public.usuarios(id) on delete set null,
  aprovado_em timestamptz,
  concluido_em timestamptz,
  cancelado_em timestamptz,
  created_by uuid references public.usuarios(id) on delete set null,
  updated_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, id),
  unique (empresa_id, idempotency_key),
  foreign key (empresa_id, parceiro_id) references public.comercial_parceiros(empresa_id, id) on delete restrict,
  foreign key (empresa_id, deposito_id) references public.estoque_depositos(empresa_id, id) on delete restrict,
  check (desconto <= subtotal + acrescimo + frete)
);
create index comercial_documentos_lista_idx on public.comercial_documentos (empresa_id, tipo, status, created_at desc);
create index comercial_documentos_parceiro_idx on public.comercial_documentos (empresa_id, parceiro_id, created_at desc);
create index comercial_documentos_contato_idx on public.comercial_documentos (empresa_id, contato_id, created_at desc) where contato_id is not null;
create index comercial_documentos_origem_idx on public.comercial_documentos (empresa_id, documento_origem_id) where documento_origem_id is not null;

create table public.comercial_documento_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  documento_id uuid not null,
  catalogo_servico_id uuid,
  estoque_item_id uuid,
  descricao text not null,
  unidade text not null default 'un',
  quantidade numeric(18,6) not null check (quantidade > 0),
  quantidade_atendida numeric(18,6) not null default 0 check (quantidade_atendida >= 0),
  valor_unitario numeric(18,6) not null default 0 check (valor_unitario >= 0),
  desconto numeric(18,2) not null default 0 check (desconto >= 0),
  total numeric(18,2) generated always as (greatest(0, round((quantidade * valor_unitario - desconto)::numeric, 2))) stored,
  deposito_id uuid,
  observacao text,
  created_at timestamptz not null default now(),
  unique (empresa_id, id),
  foreign key (empresa_id, documento_id) references public.comercial_documentos(empresa_id, id) on delete cascade,
  foreign key (empresa_id, catalogo_servico_id) references public.catalogo_servicos(empresa_id, id) on delete restrict,
  foreign key (empresa_id, deposito_id) references public.estoque_depositos(empresa_id, id) on delete restrict,
  foreign key (estoque_item_id) references public.estoque_itens(id) on delete restrict,
  check (quantidade_atendida <= quantidade)
);
create index comercial_documento_itens_documento_idx on public.comercial_documento_itens (empresa_id, documento_id);
create index comercial_documento_itens_estoque_idx on public.comercial_documento_itens (empresa_id, estoque_item_id) where estoque_item_id is not null;
create index comercial_documento_itens_catalogo_idx on public.comercial_documento_itens (empresa_id, catalogo_servico_id) where catalogo_servico_id is not null;
alter table public.estoque_reservas add column if not exists comercial_documento_item_id uuid references public.comercial_documento_itens(id) on delete restrict;
create index estoque_reservas_comercial_item_idx on public.estoque_reservas (empresa_id,comercial_documento_item_id) where comercial_documento_item_id is not null;

create table public.comercial_pagamentos (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  documento_id uuid not null,
  tipo text not null check (tipo in ('receber','pagar')),
  status text not null default 'pendente' check (status in ('pendente','confirmado','cancelado','estornado')),
  forma text not null default 'outro' check (forma in ('dinheiro','pix','cartao_credito','cartao_debito','boleto','transferencia','outro')),
  valor numeric(18,2) not null check (valor > 0),
  vencimento_em date,
  confirmado_em timestamptz,
  referencia text,
  observacao text,
  idempotency_key text,
  created_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (empresa_id, idempotency_key),
  foreign key (empresa_id, documento_id) references public.comercial_documentos(empresa_id, id) on delete restrict
);
create index comercial_pagamentos_documento_idx on public.comercial_pagamentos (empresa_id, documento_id, status);
create index comercial_pagamentos_vencimento_idx on public.comercial_pagamentos (empresa_id, status, vencimento_em);

create table public.estoque_inventarios (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  numero bigint generated by default as identity,
  deposito_id uuid not null,
  status text not null default 'rascunho' check (status in ('rascunho','em_contagem','aguardando_aprovacao','aprovado','cancelado')),
  tipo_contagem text not null default 'cega' check (tipo_contagem in ('aberta','cega')),
  descricao text not null,
  iniciado_em timestamptz,
  encerrado_em timestamptz,
  aprovado_em timestamptz,
  aprovado_por uuid references public.usuarios(id) on delete set null,
  documento_ajuste_id uuid references public.estoque_documentos(id) on delete restrict,
  observacao text,
  created_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, id),
  foreign key (empresa_id, deposito_id) references public.estoque_depositos(empresa_id, id) on delete restrict
);
create index estoque_inventarios_lista_idx on public.estoque_inventarios (empresa_id, status, created_at desc);

create table public.estoque_inventario_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  inventario_id uuid not null,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  lote_id uuid,
  saldo_esperado numeric(18,6) not null default 0 check (saldo_esperado >= 0),
  primeira_contagem numeric(18,6) check (primeira_contagem is null or primeira_contagem >= 0),
  segunda_contagem numeric(18,6) check (segunda_contagem is null or segunda_contagem >= 0),
  quantidade_aprovada numeric(18,6) check (quantidade_aprovada is null or quantidade_aprovada >= 0),
  divergencia numeric(18,6) generated always as (coalesce(quantidade_aprovada, segunda_contagem, primeira_contagem, saldo_esperado) - saldo_esperado) stored,
  justificativa text,
  contado_por uuid references public.usuarios(id) on delete set null,
  contado_em timestamptz,
  unique (empresa_id, inventario_id, estoque_item_id, lote_id),
  foreign key (empresa_id, inventario_id) references public.estoque_inventarios(empresa_id, id) on delete cascade,
  foreign key (empresa_id, lote_id) references public.estoque_lotes(empresa_id, id) on delete restrict
);
create index estoque_inventario_itens_inventario_idx on public.estoque_inventario_itens (empresa_id, inventario_id);
create index estoque_inventario_itens_item_idx on public.estoque_inventario_itens (empresa_id, estoque_item_id);
create unique index estoque_inventario_itens_sem_lote_uk on public.estoque_inventario_itens (empresa_id,inventario_id,estoque_item_id) where lote_id is null;

create or replace function public.comercial_recalcular_documento(p_empresa_id uuid, p_documento_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare v_subtotal numeric(18,2);
begin
  select coalesce(sum(total),0) into v_subtotal from public.comercial_documento_itens
   where empresa_id=p_empresa_id and documento_id=p_documento_id;
  update public.comercial_documentos set subtotal=v_subtotal,
    total=greatest(0, v_subtotal-desconto+acrescimo+frete), updated_at=now()
   where empresa_id=p_empresa_id and id=p_documento_id;
end $$;

create or replace function public.comercial_salvar_documento(
  p_empresa_id uuid, p_documento_id uuid, p_tipo text, p_parceiro_id uuid, p_contato_id uuid,
  p_deposito_id uuid, p_data_emissao date, p_validade_em date, p_previsao_em date,
  p_desconto numeric, p_acrescimo numeric, p_frete numeric, p_observacao text,
  p_itens jsonb, p_usuario_id uuid
) returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_item jsonb; v_catalogo public.catalogo_servicos%rowtype; v_estoque public.estoque_itens%rowtype;
begin
  if p_tipo not in ('orcamento','pedido_venda','venda','pedido_compra') then raise exception 'Tipo de documento invalido.'; end if;
  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens)=0 then raise exception 'Informe ao menos um item.'; end if;
  if p_documento_id is null then
    insert into public.comercial_documentos(empresa_id,tipo,parceiro_id,contato_id,deposito_id,data_emissao,validade_em,previsao_em,desconto,acrescimo,frete,observacao,created_by,updated_by)
    values(p_empresa_id,p_tipo,p_parceiro_id,p_contato_id,p_deposito_id,coalesce(p_data_emissao,current_date),p_validade_em,p_previsao_em,greatest(0,coalesce(p_desconto,0)),greatest(0,coalesce(p_acrescimo,0)),greatest(0,coalesce(p_frete,0)),nullif(trim(p_observacao),''),p_usuario_id,p_usuario_id)
    returning id into v_id;
  else
    select id into v_id from public.comercial_documentos where empresa_id=p_empresa_id and id=p_documento_id and status='rascunho' for update;
    if v_id is null then raise exception 'Somente documentos em rascunho podem ser editados.'; end if;
    update public.comercial_documentos set tipo=p_tipo,parceiro_id=p_parceiro_id,contato_id=p_contato_id,deposito_id=p_deposito_id,
      data_emissao=coalesce(p_data_emissao,current_date),validade_em=p_validade_em,previsao_em=p_previsao_em,
      desconto=greatest(0,coalesce(p_desconto,0)),acrescimo=greatest(0,coalesce(p_acrescimo,0)),frete=greatest(0,coalesce(p_frete,0)),
      observacao=nullif(trim(p_observacao),''),updated_by=p_usuario_id,updated_at=now(),versao=versao+1 where id=v_id;
    delete from public.comercial_documento_itens where empresa_id=p_empresa_id and documento_id=v_id;
  end if;
  if p_parceiro_id is not null and not exists(select 1 from public.comercial_parceiros where empresa_id=p_empresa_id and id=p_parceiro_id and ativo) then raise exception 'Parceiro invalido.'; end if;
  if p_contato_id is not null and not exists(select 1 from public.contatos where empresa_id=p_empresa_id and id=p_contato_id) then raise exception 'Contato invalido.'; end if;
  for v_item in select value from jsonb_array_elements(p_itens) loop
    v_catalogo := null; v_estoque := null;
    if nullif(v_item->>'catalogo_servico_id','') is not null then select * into v_catalogo from public.catalogo_servicos where empresa_id=p_empresa_id and id=(v_item->>'catalogo_servico_id')::uuid and ativo; end if;
    if nullif(v_item->>'estoque_item_id','') is not null then select * into v_estoque from public.estoque_itens where empresa_id=p_empresa_id and id=(v_item->>'estoque_item_id')::uuid and ativo; end if;
    if v_catalogo.id is null and v_estoque.id is null then raise exception 'Item do documento invalido.'; end if;
    insert into public.comercial_documento_itens(empresa_id,documento_id,catalogo_servico_id,estoque_item_id,descricao,unidade,quantidade,valor_unitario,desconto,deposito_id,observacao)
    values(p_empresa_id,v_id,v_catalogo.id,coalesce(v_estoque.id,v_catalogo.estoque_item_id),coalesce(nullif(v_item->>'descricao',''),v_catalogo.nome,v_estoque.nome),
      coalesce(nullif(v_item->>'unidade',''),v_catalogo.unidade,v_estoque.unidade,'un'),greatest(0,(v_item->>'quantidade')::numeric),
      greatest(0,coalesce((v_item->>'valor_unitario')::numeric,v_catalogo.preco,v_estoque.preco_venda,0)),greatest(0,coalesce((v_item->>'desconto')::numeric,0)),
      coalesce(nullif(v_item->>'deposito_id','')::uuid,p_deposito_id,v_catalogo.deposito_padrao_id),nullif(v_item->>'observacao',''));
  end loop;
  perform public.comercial_recalcular_documento(p_empresa_id,v_id);
  return v_id;
end $$;

create or replace function public.comercial_reservar_pedido(p_empresa_id uuid,p_documento_id uuid,p_usuario_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_doc public.comercial_documentos%rowtype; v_item record; v_saldo record; v_falta numeric; v_alocar numeric; v_total integer:=0;
begin
  select * into v_doc from public.comercial_documentos where empresa_id=p_empresa_id and id=p_documento_id for update;
  if v_doc.tipo not in ('pedido_venda','venda') then raise exception 'Documento nao e uma venda.'; end if;
  if v_doc.status in ('aprovado','parcial','concluido') then return jsonb_build_object('idempotente',true); end if;
  if v_doc.status not in ('rascunho','enviado') then raise exception 'Documento nao pode ser aprovado.'; end if;
  for v_item in select * from public.comercial_documento_itens where empresa_id=p_empresa_id and documento_id=p_documento_id and estoque_item_id is not null order by estoque_item_id loop
    v_falta:=v_item.quantidade;
    for v_saldo in select s.* from public.estoque_saldos s left join public.estoque_lotes l on l.id=s.lote_id
      where s.empresa_id=p_empresa_id and s.estoque_item_id=v_item.estoque_item_id and s.deposito_id=coalesce(v_item.deposito_id,v_doc.deposito_id)
        and s.saldo_fisico>s.saldo_reservado and coalesce(l.bloqueado,false)=false and (l.validade is null or l.validade>=current_date)
      order by l.validade asc nulls last,s.updated_at for update of s
    loop
      v_alocar:=least(v_falta,v_saldo.saldo_fisico-v_saldo.saldo_reservado);
      update public.estoque_saldos set saldo_reservado=saldo_reservado+v_alocar,versao=versao+1,updated_at=now() where id=v_saldo.id;
      insert into public.estoque_reservas(empresa_id,estoque_item_id,deposito_id,lote_id,quantidade,status,origem_tipo,origem_id,created_by,saldo_id,comercial_documento_item_id)
      values(p_empresa_id,v_item.estoque_item_id,v_saldo.deposito_id,v_saldo.lote_id,v_alocar,'ativa','pedido_venda',p_documento_id,p_usuario_id,v_saldo.id,v_item.id);
      v_falta:=v_falta-v_alocar; v_total:=v_total+1; exit when v_falta<=0;
    end loop;
    if v_falta>0 then raise exception 'Saldo insuficiente para reservar %.',v_item.descricao; end if;
  end loop;
  update public.comercial_documentos set status='aprovado',aprovado_por=p_usuario_id,aprovado_em=now(),updated_at=now() where id=p_documento_id;
  return jsonb_build_object('reservas',v_total);
end $$;

create or replace function public.comercial_liberar_pedido(p_empresa_id uuid,p_documento_id uuid,p_usuario_id uuid,p_cancelar boolean default true)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_reserva record; v_total integer:=0;
begin
  for v_reserva in select * from public.estoque_reservas where empresa_id=p_empresa_id and origem_tipo='pedido_venda' and origem_id=p_documento_id and status='ativa' order by saldo_id for update loop
    update public.estoque_saldos set saldo_reservado=greatest(0,saldo_reservado-(v_reserva.quantidade-v_reserva.consumida)),versao=versao+1,updated_at=now() where empresa_id=p_empresa_id and id=v_reserva.saldo_id;
    update public.estoque_reservas set status='liberada',updated_by=p_usuario_id,updated_at=now() where id=v_reserva.id;
    v_total:=v_total+1;
  end loop;
  if p_cancelar then update public.comercial_documentos set status='cancelado',cancelado_em=now(),updated_by=p_usuario_id,updated_at=now() where empresa_id=p_empresa_id and id=p_documento_id and status<>'concluido'; end if;
  return jsonb_build_object('reservas_liberadas',v_total);
end $$;

create or replace function public.comercial_atender_documento(p_empresa_id uuid,p_documento_id uuid,p_usuario_id uuid,p_idempotency_key text,p_quantidades jsonb default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_doc public.comercial_documentos%rowtype; v_item record; v_reserva record; v_linha public.comercial_documento_itens%rowtype; v_estoque_doc uuid; v_tipo text; v_qtd numeric; v_solicitada numeric; v_total integer:=0; v_pendente boolean;
begin
  select * into v_doc from public.comercial_documentos where empresa_id=p_empresa_id and id=p_documento_id for update;
  if not found then raise exception 'Documento nao encontrado.'; end if;
  if v_doc.status='concluido' then return jsonb_build_object('idempotente',true); end if;
  if v_doc.tipo in ('pedido_compra') then v_tipo:='entrada';
  elsif v_doc.tipo in ('pedido_venda','venda') then v_tipo:='saida';
  else raise exception 'Documento nao pode ser atendido.'; end if;
  if v_tipo='saida' and v_doc.status not in ('aprovado','parcial') then perform public.comercial_reservar_pedido(p_empresa_id,p_documento_id,p_usuario_id); end if;
  insert into public.estoque_documentos(empresa_id,tipo,status,origem_tipo,origem_id,idempotency_key,observacao,created_by)
  values(p_empresa_id,v_tipo,'rascunho',v_doc.tipo,p_documento_id,coalesce(nullif(p_idempotency_key,''),p_documento_id::text||':atender'),v_doc.observacao,p_usuario_id)
  on conflict(empresa_id,idempotency_key) do nothing returning id into v_estoque_doc;
  if v_estoque_doc is null then return jsonb_build_object('idempotente',true); end if;
  if v_tipo='entrada' then
    for v_item in select * from public.comercial_documento_itens where empresa_id=p_empresa_id and documento_id=p_documento_id and estoque_item_id is not null and quantidade_atendida<quantidade order by estoque_item_id loop
      v_solicitada:=coalesce((select (value->>'quantidade')::numeric from jsonb_array_elements(coalesce(p_quantidades,'[]'::jsonb)) where value->>'item_id'=v_item.id::text limit 1),v_item.quantidade-v_item.quantidade_atendida);
      v_qtd:=least(v_item.quantidade-v_item.quantidade_atendida,greatest(0,v_solicitada));
      continue when v_qtd<=0;
      insert into public.estoque_documento_itens(empresa_id,documento_id,estoque_item_id,deposito_destino_id,quantidade,custo_unitario)
      values(p_empresa_id,v_estoque_doc,v_item.estoque_item_id,coalesce(v_item.deposito_id,v_doc.deposito_id),v_qtd,v_item.valor_unitario);
      update public.comercial_documento_itens set quantidade_atendida=quantidade_atendida+v_qtd where id=v_item.id;
      v_total:=v_total+1;
    end loop;
  else
    for v_reserva in select * from public.estoque_reservas where empresa_id=p_empresa_id and origem_tipo='pedido_venda' and origem_id=p_documento_id and status='ativa' order by estoque_item_id,saldo_id for update loop
      select * into v_linha from public.comercial_documento_itens where id=v_reserva.comercial_documento_item_id for update;
      v_solicitada:=coalesce((select (value->>'quantidade')::numeric from jsonb_array_elements(coalesce(p_quantidades,'[]'::jsonb)) where value->>'item_id'=v_linha.id::text limit 1),v_linha.quantidade);
      v_qtd:=least(v_reserva.quantidade-v_reserva.consumida,greatest(0,v_solicitada-v_linha.quantidade_atendida));
      continue when v_qtd<=0;
      update public.estoque_saldos set saldo_reservado=greatest(0,saldo_reservado-v_qtd),versao=versao+1,updated_at=now() where id=v_reserva.saldo_id;
      insert into public.estoque_documento_itens(empresa_id,documento_id,estoque_item_id,deposito_origem_id,lote_id,quantidade,custo_unitario)
      select p_empresa_id,v_estoque_doc,v_reserva.estoque_item_id,v_reserva.deposito_id,v_reserva.lote_id,v_qtd,s.custo_medio from public.estoque_saldos s where s.id=v_reserva.saldo_id;
      update public.estoque_reservas set consumida=consumida+v_qtd,status=case when consumida+v_qtd>=quantidade then 'consumida' else status end,consumida_em=case when consumida+v_qtd>=quantidade then now() else consumida_em end,updated_by=p_usuario_id,updated_at=now() where id=v_reserva.id;
      update public.comercial_documento_itens set quantidade_atendida=quantidade_atendida+v_qtd where id=v_linha.id;
      v_total:=v_total+1;
    end loop;
  end if;
  if v_total=0 then raise exception 'Documento sem itens de estoque pendentes.'; end if;
  perform public.estoque_confirmar_documento(p_empresa_id,v_estoque_doc,p_usuario_id);
  select exists(select 1 from public.comercial_documento_itens where empresa_id=p_empresa_id and documento_id=p_documento_id and estoque_item_id is not null and quantidade_atendida<quantidade) into v_pendente;
  update public.comercial_documentos set status=case when v_pendente then 'parcial' else 'concluido' end,concluido_em=case when v_pendente then null else now() end,updated_by=p_usuario_id,updated_at=now() where id=p_documento_id;
  return jsonb_build_object('documento_estoque_id',v_estoque_doc,'itens',v_total);
end $$;

create or replace function public.comercial_devolver_documento(p_empresa_id uuid,p_documento_id uuid,p_usuario_id uuid,p_idempotency_key text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_origem public.comercial_documentos%rowtype; v_devolucao uuid; v_estoque_doc uuid; v_item record; v_tipo_comercial text; v_tipo_estoque text; v_total integer:=0;
begin
  select * into v_origem from public.comercial_documentos where empresa_id=p_empresa_id and id=p_documento_id and status='concluido' for update;
  if not found then raise exception 'Somente documentos concluidos podem ser devolvidos.'; end if;
  if v_origem.tipo='pedido_compra' then v_tipo_comercial:='devolucao_compra'; v_tipo_estoque:='saida';
  elsif v_origem.tipo in ('pedido_venda','venda') then v_tipo_comercial:='devolucao_venda'; v_tipo_estoque:='entrada';
  else raise exception 'Documento nao admite devolucao.'; end if;
  select id into v_devolucao from public.comercial_documentos where empresa_id=p_empresa_id and idempotency_key=p_idempotency_key;
  if v_devolucao is not null then return jsonb_build_object('idempotente',true,'documento_id',v_devolucao); end if;
  insert into public.comercial_documentos(empresa_id,tipo,status,parceiro_id,contato_id,documento_origem_id,deposito_id,data_emissao,subtotal,total,idempotency_key,observacao,concluido_em,created_by,updated_by)
  values(p_empresa_id,v_tipo_comercial,'concluido',v_origem.parceiro_id,v_origem.contato_id,v_origem.id,v_origem.deposito_id,current_date,v_origem.subtotal,v_origem.total,p_idempotency_key,'Devolucao integral do documento '||v_origem.numero,now(),p_usuario_id,p_usuario_id)
  returning id into v_devolucao;
  insert into public.estoque_documentos(empresa_id,tipo,status,origem_tipo,origem_id,idempotency_key,observacao,created_by)
  values(p_empresa_id,v_tipo_estoque,'rascunho',v_tipo_comercial,v_devolucao,p_idempotency_key||':estoque','Devolucao do documento '||v_origem.numero,p_usuario_id) returning id into v_estoque_doc;
  for v_item in select * from public.comercial_documento_itens where empresa_id=p_empresa_id and documento_id=p_documento_id order by estoque_item_id nulls last loop
    insert into public.comercial_documento_itens(empresa_id,documento_id,catalogo_servico_id,estoque_item_id,descricao,unidade,quantidade,quantidade_atendida,valor_unitario,desconto,deposito_id,observacao)
    values(p_empresa_id,v_devolucao,v_item.catalogo_servico_id,v_item.estoque_item_id,v_item.descricao,v_item.unidade,v_item.quantidade_atendida,v_item.quantidade_atendida,v_item.valor_unitario,v_item.desconto,v_item.deposito_id,'Devolucao integral');
    if v_item.estoque_item_id is not null and v_item.quantidade_atendida>0 then
      insert into public.estoque_documento_itens(empresa_id,documento_id,estoque_item_id,deposito_origem_id,deposito_destino_id,quantidade,custo_unitario)
      select p_empresa_id,v_estoque_doc,v_item.estoque_item_id,case when v_tipo_estoque='saida' then coalesce(v_item.deposito_id,v_origem.deposito_id) end,case when v_tipo_estoque='entrada' then coalesce(v_item.deposito_id,v_origem.deposito_id) end,v_item.quantidade_atendida,
        coalesce((select max(custo_medio) from public.estoque_saldos where empresa_id=p_empresa_id and estoque_item_id=v_item.estoque_item_id),v_item.valor_unitario);
      v_total:=v_total+1;
    end if;
  end loop;
  if v_total=0 then raise exception 'Documento sem itens de estoque para devolver.'; end if;
  perform public.estoque_confirmar_documento(p_empresa_id,v_estoque_doc,p_usuario_id);
  return jsonb_build_object('documento_id',v_devolucao,'documento_estoque_id',v_estoque_doc,'itens',v_total);
end $$;

create or replace function public.comercial_registrar_pagamento(p_empresa_id uuid,p_documento_id uuid,p_valor numeric,p_forma text,p_vencimento date,p_confirmar boolean,p_referencia text,p_observacao text,p_idempotency_key text,p_usuario_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_doc public.comercial_documentos%rowtype; v_id uuid; v_tipo text;
begin
  select * into v_doc from public.comercial_documentos where empresa_id=p_empresa_id and id=p_documento_id;
  if not found then raise exception 'Documento nao encontrado.'; end if;
  v_tipo:=case when v_doc.tipo in ('pedido_compra','recebimento_compra','devolucao_venda') then 'pagar' else 'receber' end;
  insert into public.comercial_pagamentos(empresa_id,documento_id,tipo,status,forma,valor,vencimento_em,confirmado_em,referencia,observacao,idempotency_key,created_by)
  values(p_empresa_id,p_documento_id,v_tipo,case when p_confirmar then 'confirmado' else 'pendente' end,p_forma,p_valor,p_vencimento,case when p_confirmar then now() end,p_referencia,p_observacao,p_idempotency_key,p_usuario_id)
  returning id into v_id;
  update public.comercial_documentos d set valor_pago=(select coalesce(sum(valor),0) from public.comercial_pagamentos where empresa_id=p_empresa_id and documento_id=p_documento_id and status='confirmado'),updated_at=now() where d.id=p_documento_id;
  return v_id;
end $$;

create or replace function public.estoque_salvar_inventario(p_empresa_id uuid,p_inventario_id uuid,p_deposito_id uuid,p_descricao text,p_tipo_contagem text,p_itens jsonb,p_usuario_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_item jsonb; v_esperado numeric;
begin
  if p_inventario_id is null then
    insert into public.estoque_inventarios(empresa_id,deposito_id,descricao,tipo_contagem,status,iniciado_em,created_by)
    values(p_empresa_id,p_deposito_id,p_descricao,p_tipo_contagem,'em_contagem',now(),p_usuario_id) returning id into v_id;
  else
    select id into v_id from public.estoque_inventarios where empresa_id=p_empresa_id and id=p_inventario_id and status in ('rascunho','em_contagem') for update;
    if v_id is null then raise exception 'Inventario nao pode ser editado.'; end if;
    update public.estoque_inventarios set descricao=p_descricao,tipo_contagem=p_tipo_contagem,updated_at=now() where id=v_id;
  end if;
  for v_item in select value from jsonb_array_elements(p_itens) loop
    if not exists(select 1 from public.estoque_itens where empresa_id=p_empresa_id and id=(v_item->>'estoque_item_id')::uuid and ativo) then raise exception 'Item de inventario invalido.'; end if;
    select coalesce(sum(saldo_fisico),0) into v_esperado from public.estoque_saldos where empresa_id=p_empresa_id and deposito_id=p_deposito_id and estoque_item_id=(v_item->>'estoque_item_id')::uuid;
    insert into public.estoque_inventario_itens(empresa_id,inventario_id,estoque_item_id,saldo_esperado,primeira_contagem,segunda_contagem,quantidade_aprovada,justificativa,contado_por,contado_em)
    values(p_empresa_id,v_id,(v_item->>'estoque_item_id')::uuid,v_esperado,nullif(v_item->>'primeira_contagem','')::numeric,nullif(v_item->>'segunda_contagem','')::numeric,nullif(v_item->>'quantidade_aprovada','')::numeric,nullif(v_item->>'justificativa',''),p_usuario_id,now())
    on conflict(empresa_id,inventario_id,estoque_item_id) where lote_id is null do update set primeira_contagem=excluded.primeira_contagem,segunda_contagem=excluded.segunda_contagem,quantidade_aprovada=excluded.quantidade_aprovada,justificativa=excluded.justificativa,contado_por=p_usuario_id,contado_em=now();
  end loop;
  update public.estoque_inventarios set status='aguardando_aprovacao',encerrado_em=now(),updated_at=now() where id=v_id;
  return v_id;
end $$;

create or replace function public.estoque_aprovar_inventario(p_empresa_id uuid,p_inventario_id uuid,p_usuario_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_inv public.estoque_inventarios%rowtype; v_item record; v_doc uuid; v_total integer:=0;
begin
  select * into v_inv from public.estoque_inventarios where empresa_id=p_empresa_id and id=p_inventario_id for update;
  if v_inv.status='aprovado' then return jsonb_build_object('idempotente',true,'documento_id',v_inv.documento_ajuste_id); end if;
  if v_inv.status<>'aguardando_aprovacao' then raise exception 'Inventario nao aguarda aprovacao.'; end if;
  insert into public.estoque_documentos(empresa_id,tipo,status,origem_tipo,origem_id,idempotency_key,observacao,created_by)
  values(p_empresa_id,'ajuste','rascunho','inventario',p_inventario_id,'inventario:'||p_inventario_id::text,v_inv.descricao,p_usuario_id) returning id into v_doc;
  for v_item in select * from public.estoque_inventario_itens where empresa_id=p_empresa_id and inventario_id=p_inventario_id order by estoque_item_id loop
    if coalesce(v_item.quantidade_aprovada,v_item.segunda_contagem,v_item.primeira_contagem) is null then raise exception 'Todos os itens precisam ser contados.'; end if;
    if v_item.divergencia<>0 and nullif(trim(v_item.justificativa),'') is null then raise exception 'Justifique todas as divergencias.'; end if;
    insert into public.estoque_documento_itens(empresa_id,documento_id,estoque_item_id,deposito_destino_id,quantidade)
    values(p_empresa_id,v_doc,v_item.estoque_item_id,v_inv.deposito_id,coalesce(v_item.quantidade_aprovada,v_item.segunda_contagem,v_item.primeira_contagem));
    v_total:=v_total+1;
  end loop;
  perform public.estoque_confirmar_documento(p_empresa_id,v_doc,p_usuario_id);
  update public.estoque_inventarios set status='aprovado',aprovado_por=p_usuario_id,aprovado_em=now(),documento_ajuste_id=v_doc,updated_at=now() where id=p_inventario_id;
  return jsonb_build_object('documento_id',v_doc,'itens',v_total);
end $$;

do $$ declare t text; begin
  foreach t in array array['comercial_parceiros','comercial_documentos','comercial_documento_itens','comercial_pagamentos','estoque_inventarios','estoque_inventario_itens'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from anon, authenticated',t);
  end loop;
end $$;

revoke execute on function public.comercial_recalcular_documento(uuid,uuid) from public,anon,authenticated;
revoke execute on function public.comercial_salvar_documento(uuid,uuid,text,uuid,uuid,uuid,date,date,date,numeric,numeric,numeric,text,jsonb,uuid) from public,anon,authenticated;
revoke execute on function public.comercial_reservar_pedido(uuid,uuid,uuid) from public,anon,authenticated;
revoke execute on function public.comercial_liberar_pedido(uuid,uuid,uuid,boolean) from public,anon,authenticated;
revoke execute on function public.comercial_atender_documento(uuid,uuid,uuid,text,jsonb) from public,anon,authenticated;
revoke execute on function public.comercial_devolver_documento(uuid,uuid,uuid,text) from public,anon,authenticated;
revoke execute on function public.comercial_registrar_pagamento(uuid,uuid,numeric,text,date,boolean,text,text,text,uuid) from public,anon,authenticated;
revoke execute on function public.estoque_salvar_inventario(uuid,uuid,uuid,text,text,jsonb,uuid) from public,anon,authenticated;
revoke execute on function public.estoque_aprovar_inventario(uuid,uuid,uuid) from public,anon,authenticated;
grant execute on function public.comercial_recalcular_documento(uuid,uuid),public.comercial_salvar_documento(uuid,uuid,text,uuid,uuid,uuid,date,date,date,numeric,numeric,numeric,text,jsonb,uuid),public.comercial_reservar_pedido(uuid,uuid,uuid),public.comercial_liberar_pedido(uuid,uuid,uuid,boolean),public.comercial_atender_documento(uuid,uuid,uuid,text,jsonb),public.comercial_devolver_documento(uuid,uuid,uuid,text),public.comercial_registrar_pagamento(uuid,uuid,numeric,text,date,boolean,text,text,text,uuid),public.estoque_salvar_inventario(uuid,uuid,uuid,text,text,jsonb,uuid),public.estoque_aprovar_inventario(uuid,uuid,uuid) to service_role;

insert into public.permissoes(codigo,descricao) values
 ('compras.visualizar','Visualizar fornecedores e compras'),('compras.gerenciar','Criar e editar fornecedores e pedidos de compra'),('compras.aprovar','Aprovar, receber e devolver compras'),
 ('vendas.visualizar','Visualizar orcamentos, pedidos e vendas'),('vendas.gerenciar','Criar e editar orcamentos, pedidos e vendas'),('vendas.aprovar','Aprovar, entregar, cancelar e devolver vendas'),
 ('financeiro.operacional','Registrar pagamentos de compras e vendas'),('estoque.inventariar','Abrir, contar e aprovar inventarios')
on conflict(codigo) do update set descricao=excluded.descricao;

insert into public.perfil_permissoes(perfil_empresa_id,permissao_codigo)
select p.id,pe.codigo from public.perfis_empresa p cross join public.permissoes pe
where lower(p.nome)='administrador' and pe.codigo in ('compras.visualizar','compras.gerenciar','compras.aprovar','vendas.visualizar','vendas.gerenciar','vendas.aprovar','financeiro.operacional','estoque.inventariar')
on conflict do nothing;

