-- Operacao de compras integrada ao estoque ERP.
-- Fornecedores, pedidos, recebimentos parciais, XML de entrada e pagamentos
-- mantem rastreabilidade sem alterar saldos fora dos documentos de estoque.

create table if not exists public.comercial_fornecedor_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  parceiro_id uuid not null,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  codigo_fornecedor text,
  ean text,
  descricao_fornecedor text,
  ultimo_custo numeric(18,6) not null default 0 check (ultimo_custo >= 0),
  quantidade_minima numeric(18,6) not null default 0 check (quantidade_minima >= 0),
  prazo_entrega_dias integer not null default 0 check (prazo_entrega_dias >= 0),
  preferencial boolean not null default false,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (empresa_id, parceiro_id, estoque_item_id),
  foreign key (empresa_id, parceiro_id)
    references public.comercial_parceiros(empresa_id, id) on delete cascade
);

create unique index if not exists comercial_fornecedor_itens_codigo_uk
  on public.comercial_fornecedor_itens (empresa_id, parceiro_id, codigo_fornecedor)
  where codigo_fornecedor is not null and codigo_fornecedor <> '' and ativo;
create index if not exists comercial_fornecedor_itens_item_idx
  on public.comercial_fornecedor_itens (empresa_id, estoque_item_id, ativo);

create table if not exists public.comercial_recebimentos_compra (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  numero bigint generated by default as identity,
  pedido_compra_id uuid not null,
  parceiro_id uuid not null,
  deposito_id uuid not null,
  estoque_documento_id uuid not null references public.estoque_documentos(id) on delete restrict,
  status text not null default 'confirmado' check (status in ('confirmado','cancelado')),
  origem text not null default 'manual' check (origem in ('manual','xml_nfe')),
  nfe_chave text,
  nfe_numero text,
  nfe_serie text,
  nfe_emissao timestamptz,
  nfe_xml text,
  subtotal numeric(18,2) not null default 0 check (subtotal >= 0),
  frete numeric(18,2) not null default 0 check (frete >= 0),
  total numeric(18,2) not null default 0 check (total >= 0),
  observacao text,
  idempotency_key text not null,
  recebido_por uuid references public.usuarios(id) on delete set null,
  recebido_em timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (empresa_id, id),
  unique (empresa_id, idempotency_key),
  unique (empresa_id, estoque_documento_id),
  foreign key (empresa_id, pedido_compra_id)
    references public.comercial_documentos(empresa_id, id) on delete restrict,
  foreign key (empresa_id, parceiro_id)
    references public.comercial_parceiros(empresa_id, id) on delete restrict,
  foreign key (empresa_id, deposito_id)
    references public.estoque_depositos(empresa_id, id) on delete restrict
);

create unique index if not exists comercial_recebimentos_nfe_chave_uk
  on public.comercial_recebimentos_compra (empresa_id, nfe_chave)
  where nfe_chave is not null and nfe_chave <> '' and status = 'confirmado';
create index if not exists comercial_recebimentos_pedido_idx
  on public.comercial_recebimentos_compra (empresa_id, pedido_compra_id, recebido_em desc);
create index if not exists comercial_recebimentos_parceiro_idx
  on public.comercial_recebimentos_compra (empresa_id, parceiro_id, recebido_em desc);

create table if not exists public.comercial_recebimento_compra_itens (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete cascade,
  recebimento_id uuid not null,
  pedido_item_id uuid not null references public.comercial_documento_itens(id) on delete restrict,
  estoque_item_id uuid not null references public.estoque_itens(id) on delete restrict,
  deposito_id uuid not null,
  localizacao_id uuid,
  lote_id uuid,
  numero_serie text,
  codigo_fornecedor text,
  ean text,
  quantidade numeric(18,6) not null check (quantidade > 0),
  custo_unitario numeric(18,6) not null check (custo_unitario >= 0),
  total numeric(18,2) generated always as (round((quantidade * custo_unitario)::numeric, 2)) stored,
  created_at timestamptz not null default now(),
  foreign key (empresa_id, recebimento_id)
    references public.comercial_recebimentos_compra(empresa_id, id) on delete restrict,
  foreign key (empresa_id, deposito_id)
    references public.estoque_depositos(empresa_id, id) on delete restrict,
  foreign key (empresa_id, localizacao_id)
    references public.estoque_localizacoes(empresa_id, id) on delete restrict,
  foreign key (empresa_id, lote_id)
    references public.estoque_lotes(empresa_id, id) on delete restrict
);

create index if not exists comercial_recebimento_itens_recebimento_idx
  on public.comercial_recebimento_compra_itens (empresa_id, recebimento_id);
create index if not exists comercial_recebimento_itens_item_idx
  on public.comercial_recebimento_compra_itens (empresa_id, estoque_item_id, created_at desc);

create or replace function public.comercial_aprovar_pedido_compra(
  p_empresa_id uuid,
  p_documento_id uuid,
  p_usuario_id uuid
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doc public.comercial_documentos%rowtype;
begin
  select * into v_doc
    from public.comercial_documentos
   where empresa_id = p_empresa_id and id = p_documento_id
   for update;

  if not found or v_doc.tipo <> 'pedido_compra' then
    raise exception 'Pedido de compra nao encontrado.';
  end if;
  if v_doc.status in ('aprovado','parcial','concluido') then
    return jsonb_build_object('idempotente', true, 'status', v_doc.status);
  end if;
  if v_doc.status not in ('rascunho','enviado') then
    raise exception 'Pedido de compra nao pode ser aprovado.';
  end if;
  if v_doc.parceiro_id is null or v_doc.deposito_id is null then
    raise exception 'Pedido precisa de fornecedor e deposito.';
  end if;
  if not exists (
    select 1 from public.comercial_documento_itens
     where empresa_id = p_empresa_id and documento_id = p_documento_id
       and estoque_item_id is not null
  ) then
    raise exception 'Pedido sem itens de estoque.';
  end if;

  update public.comercial_documentos
     set status = 'aprovado', aprovado_por = p_usuario_id, aprovado_em = now(),
         updated_by = p_usuario_id, updated_at = now(), versao = versao + 1
   where id = p_documento_id;
  return jsonb_build_object('idempotente', false, 'status', 'aprovado');
end;
$$;

create or replace function public.comercial_cancelar_pedido_compra(
  p_empresa_id uuid,
  p_documento_id uuid,
  p_usuario_id uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_status text;
begin
  select status into v_status
    from public.comercial_documentos
   where empresa_id = p_empresa_id and id = p_documento_id and tipo = 'pedido_compra'
   for update;
  if not found then raise exception 'Pedido de compra nao encontrado.'; end if;
  if v_status not in ('rascunho','enviado','aprovado') then
    raise exception 'Pedido com recebimento ou ja encerrado nao pode ser cancelado.';
  end if;
  update public.comercial_documentos
     set status = 'cancelado', cancelado_em = now(), updated_by = p_usuario_id,
         updated_at = now(), versao = versao + 1
   where id = p_documento_id;
end;
$$;

create or replace function public.comercial_receber_compra(
  p_empresa_id uuid,
  p_documento_id uuid,
  p_deposito_id uuid,
  p_itens jsonb,
  p_usuario_id uuid,
  p_idempotency_key text,
  p_origem text default 'manual',
  p_nfe jsonb default null,
  p_observacao text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doc public.comercial_documentos%rowtype;
  v_linha public.comercial_documento_itens%rowtype;
  v_item public.estoque_itens%rowtype;
  v_entrada jsonb;
  v_recebimento_id uuid;
  v_estoque_doc_id uuid;
  v_lote_id uuid;
  v_localizacao_id uuid;
  v_deposito_id uuid;
  v_quantidade numeric(18,6);
  v_custo numeric(18,6);
  v_codigo_lote text;
  v_numero_serie text;
  v_pendente boolean;
  v_total_itens integer := 0;
  v_subtotal numeric(18,2) := 0;
begin
  if nullif(trim(coalesce(p_idempotency_key,'')), '') is null then
    raise exception 'Chave de idempotencia obrigatoria.';
  end if;
  if p_origem not in ('manual','xml_nfe') then raise exception 'Origem invalida.'; end if;
  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then
    raise exception 'Informe os itens recebidos.';
  end if;

  select r.id, r.estoque_documento_id into v_recebimento_id, v_estoque_doc_id
    from public.comercial_recebimentos_compra r
   where r.empresa_id = p_empresa_id and r.idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('idempotente', true, 'recebimento_id', v_recebimento_id,
      'documento_estoque_id', v_estoque_doc_id);
  end if;

  select * into v_doc
    from public.comercial_documentos
   where empresa_id = p_empresa_id and id = p_documento_id
   for update;
  if not found or v_doc.tipo <> 'pedido_compra' then raise exception 'Pedido de compra nao encontrado.'; end if;
  if v_doc.status not in ('aprovado','parcial') then raise exception 'Aprove o pedido antes do recebimento.'; end if;
  if v_doc.parceiro_id is null then raise exception 'Pedido sem fornecedor.'; end if;

  v_deposito_id := coalesce(p_deposito_id, v_doc.deposito_id);
  if not exists (select 1 from public.estoque_depositos where empresa_id=p_empresa_id and id=v_deposito_id and ativo) then
    raise exception 'Deposito de recebimento invalido.';
  end if;

  insert into public.estoque_documentos(
    empresa_id,tipo,status,origem_tipo,origem_id,idempotency_key,observacao,created_by
  ) values (
    p_empresa_id,'entrada','rascunho','recebimento_compra',p_documento_id,
    p_idempotency_key || ':estoque',nullif(trim(coalesce(p_observacao,'')),''),p_usuario_id
  ) returning id into v_estoque_doc_id;

  insert into public.comercial_recebimentos_compra(
    empresa_id,pedido_compra_id,parceiro_id,deposito_id,estoque_documento_id,
    origem,nfe_chave,nfe_numero,nfe_serie,nfe_emissao,nfe_xml,frete,observacao,
    idempotency_key,recebido_por
  ) values (
    p_empresa_id,p_documento_id,v_doc.parceiro_id,v_deposito_id,v_estoque_doc_id,
    p_origem,nullif(p_nfe->>'chave',''),nullif(p_nfe->>'numero',''),nullif(p_nfe->>'serie',''),
    nullif(p_nfe->>'emissao','')::timestamptz,nullif(p_nfe->>'xml',''),
    greatest(0,coalesce(nullif(p_nfe->>'frete','')::numeric,0)),
    nullif(trim(coalesce(p_observacao,'')),''),p_idempotency_key,p_usuario_id
  ) returning id into v_recebimento_id;

  for v_entrada in select value from jsonb_array_elements(p_itens)
  loop
    select * into v_linha
      from public.comercial_documento_itens
     where empresa_id = p_empresa_id
       and documento_id = p_documento_id
       and id = nullif(v_entrada->>'pedido_item_id','')::uuid
     for update;
    if not found or v_linha.estoque_item_id is null then raise exception 'Item do pedido invalido.'; end if;

    select * into v_item from public.estoque_itens
     where empresa_id=p_empresa_id and id=v_linha.estoque_item_id and ativo;
    if not found then raise exception 'Item de estoque invalido.'; end if;

    v_quantidade := coalesce(nullif(v_entrada->>'quantidade','')::numeric,0);
    v_custo := coalesce(nullif(v_entrada->>'custo_unitario','')::numeric,v_linha.valor_unitario,0);
    if v_quantidade <= 0 then raise exception 'Quantidade recebida deve ser maior que zero.'; end if;
    if v_quantidade > v_linha.quantidade - v_linha.quantidade_atendida then
      raise exception 'Quantidade recebida maior que a pendente para %.', v_linha.descricao;
    end if;
    if v_custo < 0 then raise exception 'Custo unitario invalido.'; end if;

    v_localizacao_id := nullif(v_entrada->>'localizacao_id','')::uuid;
    if v_localizacao_id is not null and not exists (
      select 1 from public.estoque_localizacoes
       where empresa_id=p_empresa_id and id=v_localizacao_id and deposito_id=v_deposito_id and ativo
    ) then raise exception 'Localizacao nao pertence ao deposito.'; end if;

    v_codigo_lote := nullif(trim(coalesce(v_entrada->>'lote_codigo','')),'');
    v_lote_id := null;
    if v_item.controla_lote or v_item.controla_validade or v_codigo_lote is not null then
      if v_codigo_lote is null then raise exception 'Informe o lote de %.', v_item.nome; end if;
      insert into public.estoque_lotes(
        empresa_id,estoque_item_id,codigo,fabricado_em,validade,fabricante
      ) values (
        p_empresa_id,v_item.id,v_codigo_lote,
        nullif(v_entrada->>'fabricado_em','')::date,
        nullif(v_entrada->>'validade','')::date,
        nullif(trim(coalesce(v_entrada->>'fabricante','')),'')
      ) on conflict (empresa_id,estoque_item_id,codigo) do update set
        fabricado_em=coalesce(excluded.fabricado_em,estoque_lotes.fabricado_em),
        validade=coalesce(excluded.validade,estoque_lotes.validade),
        fabricante=coalesce(excluded.fabricante,estoque_lotes.fabricante)
      returning id into v_lote_id;
      if v_item.controla_validade and not exists (
        select 1 from public.estoque_lotes where id=v_lote_id and validade is not null
      ) then raise exception 'Informe a validade de %.',v_item.nome; end if;
    end if;

    v_numero_serie := nullif(trim(coalesce(v_entrada->>'numero_serie','')),'');
    if v_item.controla_serie and (v_numero_serie is null or v_quantidade <> 1) then
      raise exception 'Item % exige uma unidade e numero de serie.', v_item.nome;
    end if;

    insert into public.estoque_documento_itens(
      empresa_id,documento_id,estoque_item_id,deposito_destino_id,
      localizacao_destino_id,lote_id,numero_serie,quantidade,custo_unitario
    ) values (
      p_empresa_id,v_estoque_doc_id,v_item.id,v_deposito_id,
      v_localizacao_id,v_lote_id,v_numero_serie,v_quantidade,v_custo
    );

    insert into public.comercial_recebimento_compra_itens(
      empresa_id,recebimento_id,pedido_item_id,estoque_item_id,deposito_id,
      localizacao_id,lote_id,numero_serie,codigo_fornecedor,ean,quantidade,custo_unitario
    ) values (
      p_empresa_id,v_recebimento_id,v_linha.id,v_item.id,v_deposito_id,
      v_localizacao_id,v_lote_id,v_numero_serie,
      nullif(trim(coalesce(v_entrada->>'codigo_fornecedor','')),''),
      nullif(regexp_replace(coalesce(v_entrada->>'ean',''),'[^0-9]','','g'),''),
      v_quantidade,v_custo
    );

    update public.comercial_documento_itens
       set quantidade_atendida = quantidade_atendida + v_quantidade
     where id = v_linha.id;

    insert into public.comercial_fornecedor_itens(
      empresa_id,parceiro_id,estoque_item_id,codigo_fornecedor,ean,
      descricao_fornecedor,ultimo_custo,prazo_entrega_dias
    ) values (
      p_empresa_id,v_doc.parceiro_id,v_item.id,
      nullif(trim(coalesce(v_entrada->>'codigo_fornecedor','')),''),
      nullif(regexp_replace(coalesce(v_entrada->>'ean',''),'[^0-9]','','g'),''),
      v_linha.descricao,v_custo,
      (select prazo_entrega_dias from public.comercial_parceiros where id=v_doc.parceiro_id)
    ) on conflict (empresa_id,parceiro_id,estoque_item_id) do update set
      codigo_fornecedor=coalesce(excluded.codigo_fornecedor,comercial_fornecedor_itens.codigo_fornecedor),
      ean=coalesce(excluded.ean,comercial_fornecedor_itens.ean),
      descricao_fornecedor=excluded.descricao_fornecedor,
      ultimo_custo=excluded.ultimo_custo,
      updated_at=now(),ativo=true;

    v_subtotal := v_subtotal + round(v_quantidade * v_custo,2);
    v_total_itens := v_total_itens + 1;
  end loop;

  if v_total_itens = 0 then raise exception 'Recebimento sem itens.'; end if;
  perform public.estoque_confirmar_documento(p_empresa_id,v_estoque_doc_id,p_usuario_id);

  update public.comercial_recebimentos_compra
     set subtotal=v_subtotal,total=v_subtotal+frete
   where id=v_recebimento_id;

  select exists(
    select 1 from public.comercial_documento_itens
     where empresa_id=p_empresa_id and documento_id=p_documento_id
       and estoque_item_id is not null and quantidade_atendida<quantidade
  ) into v_pendente;

  update public.comercial_documentos
     set status=case when v_pendente then 'parcial' else 'concluido' end,
         concluido_em=case when v_pendente then null else now() end,
         updated_by=p_usuario_id,updated_at=now(),versao=versao+1
   where id=p_documento_id;

  return jsonb_build_object(
    'idempotente',false,'recebimento_id',v_recebimento_id,
    'documento_estoque_id',v_estoque_doc_id,'itens',v_total_itens,
    'status_pedido',case when v_pendente then 'parcial' else 'concluido' end
  );
end;
$$;

create or replace function public.comercial_registrar_pagamento_compra(
  p_empresa_id uuid,
  p_documento_id uuid,
  p_valor numeric,
  p_forma text,
  p_vencimento date,
  p_confirmar boolean,
  p_referencia text,
  p_observacao text,
  p_idempotency_key text,
  p_usuario_id uuid
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare v_doc public.comercial_documentos%rowtype; v_pago numeric; v_id uuid;
begin
  select * into v_doc from public.comercial_documentos
   where empresa_id=p_empresa_id and id=p_documento_id and tipo='pedido_compra'
   for update;
  if not found then raise exception 'Pedido de compra nao encontrado.'; end if;
  if v_doc.status='cancelado' then raise exception 'Pedido cancelado nao aceita pagamento.'; end if;
  if coalesce(p_valor,0)<=0 then raise exception 'Valor do pagamento invalido.'; end if;
  select coalesce(sum(valor),0) into v_pago from public.comercial_pagamentos
   where empresa_id=p_empresa_id and documento_id=p_documento_id and status='confirmado';
  if p_confirmar and v_pago+p_valor>v_doc.total then raise exception 'Pagamento excede o total do pedido.'; end if;
  v_id := public.comercial_registrar_pagamento(
    p_empresa_id,p_documento_id,p_valor,p_forma,p_vencimento,p_confirmar,
    p_referencia,p_observacao,p_idempotency_key,p_usuario_id
  );
  return v_id;
end;
$$;

create or replace function public.comercial_importar_receber_xml(
  p_empresa_id uuid,
  p_fornecedor jsonb,
  p_deposito_id uuid,
  p_itens jsonb,
  p_nfe jsonb,
  p_usuario_id uuid,
  p_idempotency_key text,
  p_observacao text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_parceiro_id uuid;
  v_documento_id uuid;
  v_pedido_item_id uuid;
  v_entrada jsonb;
  v_receber_itens jsonb := '[]'::jsonb;
  v_documento_fornecedor text;
  v_resultado jsonb;
begin
  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens)=0 then
    raise exception 'XML sem itens vinculados ao estoque.';
  end if;
  if nullif(regexp_replace(coalesce(p_nfe->>'chave',''),'[^0-9]','','g'),'') is null then
    raise exception 'Chave da NF-e nao informada.';
  end if;

  if exists (
    select 1 from public.comercial_recebimentos_compra
     where empresa_id=p_empresa_id and nfe_chave=regexp_replace(p_nfe->>'chave','[^0-9]','','g')
       and status='confirmado'
  ) then raise exception 'Esta NF-e ja foi recebida.'; end if;

  v_parceiro_id := nullif(p_fornecedor->>'id','')::uuid;
  v_documento_fornecedor := nullif(regexp_replace(coalesce(p_fornecedor->>'documento',''),'[^0-9A-Za-z]','','g'),'');

  if v_parceiro_id is not null then
    if not exists(select 1 from public.comercial_parceiros where empresa_id=p_empresa_id and id=v_parceiro_id and ativo) then
      raise exception 'Fornecedor selecionado e invalido.';
    end if;
  elsif v_documento_fornecedor is not null then
    select id into v_parceiro_id from public.comercial_parceiros
     where empresa_id=p_empresa_id
       and regexp_replace(coalesce(documento,''),'[^0-9A-Za-z]','','g')=v_documento_fornecedor
       and ativo limit 1;
  end if;

  if v_parceiro_id is null then
    if nullif(trim(coalesce(p_fornecedor->>'nome','')),'') is null then
      raise exception 'Fornecedor do XML sem nome.';
    end if;
    insert into public.comercial_parceiros(
      empresa_id,tipo,tipo_pessoa,nome,nome_fantasia,documento,inscricao_estadual,
      email,telefone,cep,endereco,numero,complemento,bairro,cidade,estado,
      observacao,created_by,updated_by
    ) values (
      p_empresa_id,'fornecedor','juridica',trim(p_fornecedor->>'nome'),
      nullif(trim(coalesce(p_fornecedor->>'nome_fantasia','')),''),v_documento_fornecedor,
      nullif(trim(coalesce(p_fornecedor->>'inscricao_estadual','')),''),
      nullif(trim(coalesce(p_fornecedor->>'email','')),''),nullif(trim(coalesce(p_fornecedor->>'telefone','')),''),
      nullif(regexp_replace(coalesce(p_fornecedor->>'cep',''),'[^0-9]','','g'),''),
      nullif(trim(coalesce(p_fornecedor->>'endereco','')),''),nullif(trim(coalesce(p_fornecedor->>'numero','')),''),
      nullif(trim(coalesce(p_fornecedor->>'complemento','')),''),nullif(trim(coalesce(p_fornecedor->>'bairro','')),''),
      nullif(trim(coalesce(p_fornecedor->>'cidade','')),''),upper(nullif(trim(coalesce(p_fornecedor->>'estado','')),'')),
      'Cadastrado pela importacao da NF-e '||coalesce(p_nfe->>'numero',''),p_usuario_id,p_usuario_id
    ) returning id into v_parceiro_id;
  end if;

  insert into public.comercial_documentos(
    empresa_id,tipo,status,parceiro_id,deposito_id,data_emissao,previsao_em,
    frete,observacao,idempotency_key,created_by,updated_by
  ) values (
    p_empresa_id,'pedido_compra','rascunho',v_parceiro_id,p_deposito_id,
    coalesce(nullif(left(coalesce(p_nfe->>'emissao',''),10),'')::date,current_date),current_date,
    greatest(0,coalesce(nullif(p_nfe->>'frete','')::numeric,0)),
    coalesce(nullif(trim(coalesce(p_observacao,'')),''),'Importado da NF-e '||coalesce(p_nfe->>'numero','')),
    p_idempotency_key||':pedido',p_usuario_id,p_usuario_id
  ) returning id into v_documento_id;

  for v_entrada in select value from jsonb_array_elements(p_itens)
  loop
    if not exists (
      select 1 from public.estoque_itens
       where empresa_id=p_empresa_id and id=nullif(v_entrada->>'estoque_item_id','')::uuid and ativo
    ) then raise exception 'Todos os produtos da NF-e precisam ser vinculados ao estoque.'; end if;
    if coalesce(nullif(v_entrada->>'quantidade','')::numeric,0)<=0 then raise exception 'Quantidade de item invalida.'; end if;

    insert into public.comercial_documento_itens(
      empresa_id,documento_id,estoque_item_id,descricao,unidade,quantidade,
      valor_unitario,desconto,deposito_id,observacao
    ) values (
      p_empresa_id,v_documento_id,(v_entrada->>'estoque_item_id')::uuid,
      coalesce(nullif(v_entrada->>'descricao',''),(select nome from public.estoque_itens where id=(v_entrada->>'estoque_item_id')::uuid)),
      coalesce(nullif(v_entrada->>'unidade',''),(select unidade from public.estoque_itens where id=(v_entrada->>'estoque_item_id')::uuid),'un'),
      (v_entrada->>'quantidade')::numeric,greatest(0,coalesce(nullif(v_entrada->>'custo_unitario','')::numeric,0)),0,
      p_deposito_id,'Produto '||coalesce(v_entrada->>'codigo_fornecedor','')||' da NF-e'
    ) returning id into v_pedido_item_id;

    v_receber_itens := v_receber_itens || jsonb_build_array(
      v_entrada || jsonb_build_object('pedido_item_id',v_pedido_item_id)
    );
  end loop;

  perform public.comercial_recalcular_documento(p_empresa_id,v_documento_id);
  perform public.comercial_aprovar_pedido_compra(p_empresa_id,v_documento_id,p_usuario_id);
  v_resultado := public.comercial_receber_compra(
    p_empresa_id,v_documento_id,p_deposito_id,v_receber_itens,p_usuario_id,
    p_idempotency_key,'xml_nfe',p_nfe || jsonb_build_object('chave',regexp_replace(p_nfe->>'chave','[^0-9]','','g')),
    p_observacao
  );
  return v_resultado || jsonb_build_object('pedido_id',v_documento_id,'fornecedor_id',v_parceiro_id);
end;
$$;

do $$ declare t text; begin
  foreach t in array array[
    'comercial_fornecedor_itens','comercial_recebimentos_compra','comercial_recebimento_compra_itens'
  ] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from anon, authenticated',t);
  end loop;
end $$;

revoke execute on function public.comercial_aprovar_pedido_compra(uuid,uuid,uuid) from public,anon,authenticated;
revoke execute on function public.comercial_cancelar_pedido_compra(uuid,uuid,uuid) from public,anon,authenticated;
revoke execute on function public.comercial_receber_compra(uuid,uuid,uuid,jsonb,uuid,text,text,jsonb,text) from public,anon,authenticated;
revoke execute on function public.comercial_registrar_pagamento_compra(uuid,uuid,numeric,text,date,boolean,text,text,text,uuid) from public,anon,authenticated;
revoke execute on function public.comercial_importar_receber_xml(uuid,jsonb,uuid,jsonb,jsonb,uuid,text,text) from public,anon,authenticated;

grant execute on function public.comercial_aprovar_pedido_compra(uuid,uuid,uuid) to service_role;
grant execute on function public.comercial_cancelar_pedido_compra(uuid,uuid,uuid) to service_role;
grant execute on function public.comercial_receber_compra(uuid,uuid,uuid,jsonb,uuid,text,text,jsonb,text) to service_role;
grant execute on function public.comercial_registrar_pagamento_compra(uuid,uuid,numeric,text,date,boolean,text,text,text,uuid) to service_role;
grant execute on function public.comercial_importar_receber_xml(uuid,jsonb,uuid,jsonb,jsonb,uuid,text,text) to service_role;
